name: Validate

on:
  pull_request:
    branches: [ main ]

jobs:
  # validate-pull-request:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  # validate-branch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  validate-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Unit Tests
        run: |
          python -m unittest discover tests